# Generated by Django 5.2.8 on 2025-11-22 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last name', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('surname', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('ST', 'Student'), ('T', 'Teacher'), ('O', 'Other')], default='ST')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student course title', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=5)),
                ('participants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
