# Generated by Django 5.2.8 on 2025-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student group',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
