# Generated by Django 5.2.8 on 2025-11-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='student group',
            new_name='group',
        ),
    ]
