# Generated by Django 5.2.8 on 2025-11-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_student_group_profile_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last name',
            new_name='lastname',
        ),
    ]
