# Generated by Django 5.2.8 on 2025-11-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_last_name_profile_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
