# Generated by Django 5.2.8 on 2025-11-23 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_lastname_profile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='studentscourse',
            old_name='student course title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='studentscourse',
            name='institute',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentscourse',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AddField(
            model_name='studentscourse',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.subjects'),
        ),
    ]
