# Generated by Django 5.2.8 on 2025-11-22 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course title', models.TextField()),
                ('course description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson title', models.TextField()),
                ('lesson date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notififcation title', models.CharField(max_length=255)),
                ('notification description', models.TextField()),
                ('course_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.course')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications_lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notififcation title', models.CharField(max_length=255)),
                ('notification description', models.TextField()),
                ('lesson_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lessons')),
                ('participants', models.ManyToManyField(to='account.studentscourse')),
            ],
        ),
    ]
