# Generated by Django 5.2.8 on 2025-11-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_student_group_profile_group'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='classroom',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='lessons',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lessons',
            name='flow',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
