# Generated by Django 5.2.8 on 2025-11-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_lessons_classroom_lessons_duration_lessons_flow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='lesson date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='lesson title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='notifications_courses',
            old_name='notififcation title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='notifications_lessons',
            old_name='notification description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='notifications_lessons',
            old_name='notififcation title',
            new_name='title',
        ),
    ]
