# Generated by Django 5.2.8 on 2025-11-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_rename_course_description_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
