# Generated by Django 5.2.8 on 2025-11-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_lessons_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='comments',
            new_name='comment',
        ),
    ]
