# Generated by Django 5.2.8 on 2025-11-23 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_rename_course_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
