# Generated by Django 5.2.8 on 2025-11-23 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_subjects_and_more'),
        ('schedule', '0007_alter_lessons_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
